### ISSUE TITLE
[Feature]Waterlock extends sails-auth

### ISSUE THREAD

**Issue by listepo** [waterlock/waterlock#101]
@davidrivera, I propose to use `sails-auth` as a base for creating a new version. The idea is that `waterlock` responsible only for work with jsonwebtoken

**Comment by s-devaney** [comment]
+1

**Comment by tjwebb** [comment]
Please note that Sails.js is no longer actively maintained, and thus sails-auth and sails-generate-auth are also EOL. See here for more info: https://github.com/balderdashy/sails/issues/3429#issuecomment-165004024

Several other Sails.js modules are EOL, and the maintainers are migrating their efforts to building Trails.
- https://github.com/balderdash-projects/sails-webpack/issues/2
- https://github.com/tjwebb/sails-auth/issues/118
- https://github.com/tjwebb/sails-permissions/issues/200

etc

**Comment by duhruh** [comment]
Sails looks to still be active

**Comment by mikedevita** [comment]
it is i use it quite a bit. 👍
