### ISSUE TITLE
What is the difference between hasJsonWebToken and sessionAuth policies?

### ISSUE THREAD

**Issue by s-devaney** [waterlock/waterlock#104]
It's not clear in the documentation.

Are these the only policies?

**Comment by wayne-o** [comment]
```sessionAuth``` policy uses ```req.session``` to maintain state and is installed by Sails CLI 
```hasJsonWebToken``` uses JWT (https://github.com/waterlock/waterlock/blob/master/lib/templates/policies/hasJsonWebToken.js#L13)

One of the aims of JWT is to irradiate session state - session state makes scaling harder and are generally discouraged for a host of reasons.
