### ISSUE TITLE
Is it possible to add the token as authorization header

### ISSUE THREAD

**Issue by adriaandotcom** [waterlock/waterlock#43]
A lot of frameworks use the header for the token. Is it possible to use this in waterlock?

```
Authorization: Bearer <token>
```

I want to use [this Ember Simple Auth adapter](https://github.com/jpadilla/ember-cli-simple-auth-token).

**Comment by leejt489** [comment]
I would recommend supporting tokens in the header with `Authorization: Bearer <>`.  It seems to be a common way of doing things.

I have been having trouble determining whether setting the token in the heading or the body is preferred (would love some input from someone knowledgeable!), but if both are used, I'd recommend re-opening this as an enhancement and modifying the validator to check in both places.  Should be easy to implement, just a question of how it should be configured, or which takes precedence.

**Comment by leejt489** [comment]
@harianus and others who have run into this if you're using `ember-cli-simple-auth` you have to check for the `Bearer` prefix and strip it out.  My `hasJsonWebToken` policy looks like this:

```javascript
module.exports = function(req, res, next) {
	
	//TODO: move this header check to the token validator
	var authHeader = req.headers['authorization'];
	if (authHeader.substring(0,7) !== 'Bearer ') return res.forbidden('Authorization token not included in header');
	
	req.headers['access_token'] = authHeader.substring(7);
	waterlock.validator.validateTokenRequest(req, function(err, user){
		if(err){
			return res.forbidden(err);  
		}

		// valid request
		next();
	});
};
```

As mentioned above, something like this should go into `waterlock.validator.validateTokenRequest`

**Comment by harianus** [comment]
Thanks @leejt489 for sharing your code.
