### ISSUE TITLE
Need a session to get a JWT

### ISSUE THREAD

**Issue by cyrilchapon** [waterlock/waterlock#72]
Hello =)

First of all, apologies for my bad English, and thanks about such a wonderful module that waterlock is, you might rename it 'wonderlock' =)

I've been wondering one thing, and I feel like I'm the only one to do, so I came here just to ask it.
Is that possible, with Waterlock, to "authenticate" (true security meaning, like "proving I'm the one I pretend to"), and aquiring a JWT on the same process, without going through a session ?

I mean, I've been up to create user, login, and get a JWT, but I can't see the point of using JWT if it must be aquired via a session (I might be wrong, though).

I've been reading https://github.com/waterlock/waterlock/issues/23 and https://github.com/waterlock/waterlock/issues/39 but nobody asked the question this way, so...

Thanks =)

**Comment by joesankey** [comment]
Yeh, this library would be a lot more useful if you didn't need a session to acquire a JWT.

**Comment by listepo** [comment]
+1

**Comment by leejt489** [comment]
also see #41

**Comment by listepo** [comment]
see https://github.com/waterlock/waterlock/releases/tag/v0.1.0

**Comment by wayne-o** [comment]
I'm guessing ```includeUserInJwtResponse``` fixes this? Feel free to re-open if I'm wrong :)
