### ISSUE TITLE
Can't create custom model attributes

### ISSUE THREAD

**Issue by misterch0c** [waterlock/waterlock#78]
``` firstname: 'string',
        isDeleted: {
            type: 'boolean',
            defaultsTo: false}```

I'm trying to use local-auth and have a last/firstname. This firstname attribute is not shown when I create a user like thhis: auth/login?type=local&firstname=someuser&password=12345678&email=some@e.mail however the isDeleted field is shown with it's default value

The error suggest the attribute is null/undefined but I don't understand why is that

**Comment by wayne-o** [comment]
Hi, you can use either email or username as the identity for registering a user, once you have registered the user you need to populate the other properties. 

SO basically you register with either email or password - then once you know the user ID you can hydrate that user with your extended information.

Feel free to re-open this if you have any further queries
