### ISSUE TITLE
Add support for secret config in local.js

### ISSUE THREAD

**Issue by tibotiber** [waterlock/waterlock#80]
Hi, this issue is related to #38. I would like to leave `config/waterlock.js` gitted while moving the secret to `config/local.js`. However, when I do this the secret is not found anymore. The error is:

```
error: Sending 500 ("Server Error") response:
 Error: Require key
    at Object.jwt_encode [as encode] (/home/tibo/greeny-oms/backend/node_modules/waterlock/node_modules/jwt-simple/lib/jwt.js:103:11)
    at Object.module.exports (/home/tibo/greeny-oms/backend/node_modules/waterlock/lib/controllers/actions/jwt.js:28:19)
```

I believe this is due to your manual require of `config/waterlock.js` [here](https://github.com/waterlock/waterlock/blob/master/lib/config.js#L13). Would you consider getting the config via the global sails object `sails.config.waterlock` since it already loads the config while merging local and env dependent configs?

Thanks and great work on waterlock btw :+1:

**Comment by robksawyer** [comment]
I think this may be working now. Note: Needs more testing.

See [ab33d48e0](https://github.com/robksawyer/waterlock/commit/ab33d48e091cac48b6a06d916ef07e1dd2719494).

**Comment by wayne-o** [comment]
I can confirm these changes work - I'll get them merged in for the next release
