### ISSUE TITLE
Is it possible to authenticate with username rather than email?

### ISSUE THREAD

**Issue by andyjessop** [waterlock/waterlock#89]
I have a requirement that the email is not unique for my users so I need to authenticate with a username. Is this possible with waterlock?

**Comment by davidrivera** [comment]
Yes if you are using local auth then simply setting a username on your user model *should* cause it to authenticate via username.

**Comment by benedikt-d** [comment]
Tried to adda username on the model. I'm assuming this does not change the need for a unique email address right?

Also I ran into another issue: `"\"required\" validation rule failed for input: null"`Even if I put in a username in my POST. Not sure if this is an issue with waterlock or with sails.

```username: {
    	type: 'string',
    	unique: true,
    	required: true
    },```

**Comment by praveenaj** [comment]
I successfully registered using a username. Here's my User.js model
```
/**
 * User
 *
 * @module      :: Model
 * @description :: This is the base user model
 * @docs        :: http://waterlock.ninja/documentation
 */

module.exports = {

  attributes: require('waterlock').models.user.attributes({
    
    /* e.g.
    nickname: 'string'
    */
    username : {
      type : "string",
      unique : true
    },
   //  email: {
	  //   type: 'email',
	  //   unique: true
	  // },
	  password: {
	    type: 'string',
	    minLength: 8
	  },
	  resetToken: {
	    model: 'resetToken'
	  }
    
  }),
  
  beforeCreate: require('waterlock').models.user.beforeCreate,
  beforeUpdate: require('waterlock').models.user.beforeUpdate
};
```

but when logging in I get the following. Where to change the matching logic (username && password, instead of email && password)?
```
{
    "error": "Invalid email or password"
}
```
Thanks in advance

**Comment by rlwhatley3** [comment]
"Also I ran into another issue: "\"required\" validation rule failed for input: null"Even if I put in a username in my POST. Not sure if this is an issue with waterlock or with sails.

username: { type: 'string', unique: true, required: true }"

How did you solve this? I'm having the same issue.
