### ISSUE TITLE
Username as login credential locally

### ISSUE THREAD

**Issue by ghost** [waterlock/waterlock#9]
In `waterlock-local-auth` the default login mechanism is through email.  The readme adds that

> if you want to use a username instead of an email address you can drop in the username attribute which is a signification key causing local auth to use that to authenticate.

I'm reading this as modifying the `auth.js` template in my own project and not the source.  However, in `scope.js` the code to determine what to use as the credentials type is

```
  if(typeof def.email !== 'undefined'){
    return scopes.email(authEvent);
  }else if(typeof def.username !== 'undefined'){
    return scopes.username(authEvent);
  }else{
    throw 'Auth model must have either an email or username attribute';
  }  
```

Because the source version of the auth model defines the email property, a simple "drop" of the username attribute in my project version of the model will never get to the second if-statement.  The email attribute will always be defined.

**Comment by maxali** [comment]
username is not working for me. Does it implemented or I am missing something?
