### ISSUE TITLE
Huge Use model documents number

### ISSUE THREAD

**Issue by diegoaguilar** [waterlock/waterlock#94]
I have an application with over 9000 users for which I'm using waterlock, now I'm experiencing a general latency problem, starting with login process. What I can notice the more is that I got +1200000 documents for Use collection.

This is what my database looks like:

![image](https://cloud.githubusercontent.com/assets/2483678/8834464/f49b229e-3079-11e5-8484-8b47650aaf07.png)

What should I do to optimize this?

**Comment by listepo** [comment]
Use https://github.com/jaumard/sails-hook-schedule and remove old documents from Use collection

**Comment by wayne-o** [comment]
Closing this - if the consensus is that the solution should be a part of waterlock core then please feel free to re-open
