### ISSUE TITLE
Publish master to npm

### ISSUE THREAD

**Issue by listepo** [waterlock/waterlock#97]
See https://github.com/waterlock/waterlock/compare/v0.1.0...master and waterlock-local-auth

**Comment by davidrivera** [comment]
:+1:

**Comment by davidrivera** [comment]
@waterlock/codemonkeys anyone want to take the reins on this one, i've been kinda busy.

**Comment by wayne-o** [comment]
I think there are a couple things that still need clearing up - can I go
through the PRs and make sure everything is where it's meant to be?

This will take some time though - especially to test - if anyone can lend a
hand I'd be grateful :)

**Comment by listepo** [comment]
I want to help, and a new major version wants to write on es6(maybe with babel)

**Comment by listepo** [comment]
I think it makes sense to release beta

**Comment by listepo** [comment]
Ping

**Comment by s-devaney** [comment]
+1 (waterlock-local-auth too...)
