### ISSUE TITLE
Incompatibility with sails-permission

### ISSUE THREAD

**Issue by maissani** [waterlock/waterlock#99]
There is an issue with sails-permissions and waterlock generators that can not be used as the same time.

**Comment by tjwebb** [comment]
@maissani 
Please note that Sails.js is no longer actively maintained, and thus sails-auth and sails-generate-auth are EOL. See here for more info: https://github.com/balderdashy/sails/issues/3429#issuecomment-165004024

Several other Sails.js modules are EOL, and the maintainers are migrating their efforts to building Trails.
- https://github.com/balderdash-projects/sails-webpack/issues/2
- https://github.com/tjwebb/sails-auth/issues/118
- https://github.com/tjwebb/sails-permissions/issues/200

etc
